export const catalogGroups = [
  {
    title: "Actions",
    description: "Triggers, commands, and selected actions.",
    hrefs: [
      "button",
      "link",
      "menu",
      "toggle-button",
      "toggle-button-group",
      "toolbar",
      "file-trigger",
      "command-palette",
    ],
  },
  {
    title: "Forms",
    description: "Fields, choices, and validation.",
    hrefs: [
      "text-field",
      "text-area",
      "number-field",
      "search-field",
      "select",
      "combo-box",
      "autocomplete",
      "token-field",
      "checkbox",
      "checkbox-group",
      "radio-group",
      "switch",
      "slider",
      "form",
    ],
  },
  {
    title: "Date & color",
    description: "Structured dates, times, and colors.",
    hrefs: [
      "date-field",
      "time-field",
      "calendar",
      "range-calendar",
      "date-picker",
      "date-range-picker",
      "color-field",
      "color-swatch",
      "color-swatch-picker",
      "color-picker",
    ],
  },
  {
    title: "Display & layout",
    description: "Containers, identities, values, and loading states.",
    hrefs: [
      "card",
      "avatar",
      "skeleton",
      "spinner",
      "empty-state",
      "description-list",
      "kbd-code",
      "stat",
    ],
  },
  {
    title: "Content & feedback",
    description: "Information, navigation, and progress.",
    hrefs: [
      "badge",
      "alert",
      "tabs",
      "accordion",
      "disclosure",
      "dialog",
      "drawer",
      "popover",
      "tooltip",
      "toast",
      "progress-bar",
      "meter",
      "separator",
      "breadcrumbs",
      "pagination",
      "tag-group",
      "list-box",
      "grid-list",
      "tree",
      "drop-zone",
      "table",
      "preview-trigger",
    ],
  },
] as const;
